#default project info followed by actual injected pom-specified values.
project:
    name: raad-comparison
    version: 1.0.0
    description: Raad Converter Api used to convert all type of doc formate
info:
    build:
        artifact: ${project.artifactId}
        name: ${project.name}
        description: ${project.description}
        version: ${project.version}
---
spring:
    application:
        name: Converter
    main:
        banner-mode: "off"
    servlet:
        multipart:
            maxFileSize: -1
            maxRequestSize: -1
            enabled: true
    profiles:
        active: loc
---
logging:
    level:
        org.jodconverter: info
---
file:
    downloadLocation: \tmp
---
spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/barcoFire
        username: postgres
        password: root
        testWhileIdle: true
        validationQuery: SELECT 1
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                jdbc:
                    lob.non_contextual_creation: true
                temp:
                    use_jdbc_metadata_defaults: false
        hibernate:
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
            ddl-auto: update
        show-sql: false
    jackson:
        serialization:
            fail-on-empty-beans: false
---
# d'nt remove this comment
#https://segmentfault.com/a/1190000015129654
#https://docs.alfresco.com/6.0/tasks/OOo-subsystems-config.html
#https://docs.alfresco.com/6.0/concepts/OOoJodconverter-subsystem-props.html
#//https://github.com/LibreOffice/core/blob/master/filter/source/pdf/pdfexport.cxx#L459
#jodconverter.connectTimeout=20000
jodconverter:
    local:
        enabled: true
        port-numbers: 2004
        kill-existing-process: true
        process-timeout: 180000
        process-retry-interval: 1000
        max-tasks-per-process: 20
        task-execution-timeout: 140000
        task-queue-timeout: 90000
        working-dir: /tmp
        format-options:
            html:
                store:
                    TEXT:
                        FilterOptions: EmbedImages
---
socket:
    host: 0.0.0.0
    port: 889
---
server:
    port: 9098
    servlet:
        context-path: /api/converter