#default project info followed by actual injected pom-specified values.
project:
    name: raad-comparison
    version: 1.0.0
    description: Raad Converter Api used to convert all type of doc formate
info:
    build:
        artifact: ${project.artifactId}
        name: ${project.name}
        description: ${project.description}
        version: ${project.version}
---
spring:
    application:
        name: Converter
    main:
        banner-mode: "off"
    servlet:
        multipart:
            maxFileSize: -1
            maxRequestSize: -1
            enabled: true
    profiles:
        active: loc
---
logging:
    level:
        org.jodconverter: info
---
file:
    downloadLocation: \tmp
---
server:
    port: 9098
    servlet:
        context-path: /api/converter
---
# ===============================
# = DATA SOURCE
# ===============================
spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/barcoFire
        username: postgres
        password: root
        testWhileIdle: true
        validationQuery: SELECT 1
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                jdbc:
                    lob.non_contextual_creation: true
                temp:
                    use_jdbc_metadata_defaults: false
        hibernate:
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
            ddl-auto: update
        show-sql: false
    jackson:
        serialization:
            fail-on-empty-beans: false
---
# ===============================
# = Jwt Detail ==================
# ===============================
jwt:
    app:
        name: barco
    header: Authorization
    expires_in: 600
    secret: barco_ballistic